language: python
cache: pip
python:
  - 3.5
  - 3.6
env:
  - LOGGING=info
install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade pytest pytest-cov wheel codecov
  - python setup.py bdist_wheel
  - pip install dist/dc_qiskit_algorithms*.whl
script:
  - make coverage
after_success:
  - codecov
